### ISSUE TITLE
new boilerplate project fails to compile with Vue 2.5 and TS 2.7.2

### ISSUE THREAD

**Issue by ozeebee** [vue-typed/vue-typed#23]
Hi, 
I'm trying to create a new project with the provided template.
Once created, when I try to start with `npm start`, I get this:

```
ERROR in /Users/ajo/Temp/repos/vue-typed-project/node_modules/vue-typed/dist/lib/mixins-global.d.ts
(10,64): error TS2709: Cannot use namespace 'Vue' as a type.

ERROR in /Users/ajo/Temp/repos/vue-typed-project/node_modules/vue-typed/dist/lib/options.d.ts
(11,60): error TS2709: Cannot use namespace 'Vue' as a type.

ERROR in /Users/ajo/Temp/repos/vue-typed-project/node_modules/vue-typed/dist/lib/component.d.ts
(10,62): error TS2709: Cannot use namespace 'Vue' as a type.
webpack: Failed to compile.
```

Any idea ?

thanks,
BR

**Comment by kkokey** [comment]
I have a same issue

**Comment by MaartenStaa** [comment]
Same problem here. It seems it's caused by `import * as Vue from 'vue'` in the given file. Using `import Vue from 'vue'` instead works for me.

Maybe a new version of the package needs to be published?

**Comment by budiadiono** [comment]
This package has conflict with Vue 2.5. @MaartenStaa thanks for pointing it out! You're right, I'm working on it now.

**Comment by budiadiono** [comment]
I've just release the fix along version [2.1.4](https://github.com/vue-typed/vue-typed/releases/tag/v2.1.4). Thanks everyone! 🙏😊
